### ISSUE TITLE
[FEA] New storage class concept

### ISSUE THREAD

**Issue by sleeepyjack** [NVIDIA/cuCollections#206]
## Part of #110 (Refactor of open address data structures)
Development branch: [NVIDIA/cuCollections/refactor](https://github.com/NVIDIA/cuCollections/tree/refactor) 

### Synopsis
A conceptual list of `<key,payload>` elements that need not necessarily be contiguous in memory. For example, `vector< pair<key,value> >` or `vector<key>` and `vector<value>` (i.e., AoS vs SoA) could be valid implementations of storage.

### TODOs
- [ ] Implement classes `cuco::storage::array_of_structs` and `cuco::storage::struct_of_arrays` and (optionally) `cuco::storage::array_of_structs_of_arrays` (closes #103)
- [x] Own the mechanism of atomically updating a given slot using `cuda::atomic_ref` (closes #183)
- [x] It should provide some mechanism for loading an immutable "window" of slots. The intention is to provide a standard way of using vector load/store operations
- [x] ~~Enable querying if concurrent insert/find operations are possible~~ No longer desired due to operator mixins

### References
- https://godbolt.org/z/9bosKoW4v (distinct "ProbingScheme" and "Storage" concepts)

**Comment by PointKernel** [comment]
https://godbolt.org/z/djG6cK7j1
