### ISSUE TITLE
[FEA] Move view classes to their own header

### ISSUE THREAD

**Issue by sleeepyjack** [NVIDIA/cuCollections#208]
## Part of #110 (Refactor of open address data structures)
Development branch: [NVIDIA/cuCollections/refactor](https://github.com/NVIDIA/cuCollections/tree/refactor) 

### Synopsis
Device view classes are currently implemented as nested classes of their associated data structures. This results in

### TODOs
- [x] Regroup header files by data structure, e.g. `include/cuco/detail/static_map/{kernels.cuh, impl.inl, views.cuh, ...}`
- [x] Move views to their own header files
- [ ] To disambiguate view types among data structures, use inline namespaces as shown here: https://godbolt.org/z/4qr8MK89o
- [ ] Find a way to reduce code duplication when redefining member types/passing down tparams. Use case for CRTP, e.g., `device_view<MapType>`?

### References
- https://godbolt.org/z/4qr8MK89o

**Comment by PointKernel** [comment]
completed
