### ISSUE TITLE
[FEA] Add various new table operations

### ISSUE THREAD

**Issue by sleeepyjack** [NVIDIA/cuCollections#210]
## Part of #110 (Refactor of open address data structures)
Development branch: [NVIDIA/cuCollections/refactor](https://github.com/NVIDIA/cuCollections/tree/refactor) 

### TODOs
- [x] ~~Check if element is present in the data structure: `is_present` (alias for `contains`) + `is_absent`~~
- [x] Re-initialize the data structure: `clear` (already supported by some data structures under the alias `initialize`.
- [x] Rebuild data structure with different size: `rehash` (see #21)
- [x] Higher-order function `for_each(key, func, ...)` which applies `func` to all slots that are equivalent to `key`. (see https://github.com/sleeepyjack/warpcore/blob/master/include/warpcore/single_value_hash_table.cuh#L506 and https://github.com/sleeepyjack/warpcore/blob/master/include/warpcore/multi_value_hash_table.cuh#L607)

**Comment by PointKernel** [comment]
One reduce instead of two ballots to potentially improve `contains`: https://godbolt.org/z/qv6Ghv8M3

Not necessarily improve the performance, worth testing though

**Comment by PointKernel** [comment]
`is_absent` and `is_present` turns out to be just `contains` + output iterator if needed.

Completed
